version: 'tag-{branch}-{build}'
skip_non_tags: true
branches:
  only:
  - master
configuration: Release
init:
- cmd: >-
    cd \

    appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.3.4-windows.zip

    7z x android-sdk_r24.3.4-windows.zip > nul

    cd %APPVEYOR_BUILD_FOLDER%
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: $(AssemblyBaseVersion).0.0
  assembly_file_version: $(PackageVersion).{build}
  assembly_informational_version: $(PackageVersion)
environment:
  ANDROID_HOME: C:\android-sdk-windows
install:
- ps: >-
    cd ./build

    ./SetBuildEnv.ps1

    ./UpdateAndroidSdk.cmd

    cd ..
nuget:
  project_feed: true
build_script:
- ps: >-
    Write-Host "Configuration=${env:CONFIGURATION}"

    cd ./build

    ./Build.ps1

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.nupkg"

    cd ..
